In [1]:
from hmm_utils import *
from attraction_repulsion_function import *

In [2]:
#HMM A , B, pi

priors     = np.array([0.5,0.3,0.2])
transition = np.array([[0.85, 0.05,0.1],
                       [0.05, 0.9,0.05],
                        [1/2, 1/4, 1/4]])
emission   = np.array([[1/6, 1/6, 1/6, 1/6, 1/6, 1/6],
                    [0.1, 0.1, 0.1, 0.1, 0.1, 0.5],
                       [0.1, 0.1, 0.1, 0.1, 0.1, 0.5]])

In [3]:
# initialize HMM
hmm = HMM(3)
hmm.startprob_ = priors
hmm.transmat_ = transition
hmm.emissionprob_ = emission

In [4]:
g_w_dict = {'A': transition,
      'B': emission,
      'pi': priors}

In [5]:
def example_attraction_repulsion(g_w_dict,  x_vector, utility_params):
    
    z_star = monte_carlo_enumeration_state_attraction_repulsion(g_w = g_w_dict,
                                                            N = 1,
                                                            x_vector = x_vector,
                                                            utility_function = utility_u1_state_attraction_repulsion_function,
                                                            utility_params = utility_params )
    
    
    y_vec =  compute_y_t(z_star, np.ones([len(x_vector),6]),x_vector).astype('int')
    
    
    p_untainted_data = state_attraction_repulsion_f1(t=utility_params['t'], state=utility_params['state'], alpha = hmm.alpha(x_vector), beta = hmm.beta(x_vector),c =  1)
    p_tainted_data = state_attraction_repulsion_f1(t=utility_params['t'], state=utility_params['state'], alpha = hmm.alpha(y_vec), beta = hmm.beta(y_vec),c =  1)
    
    print('Best attack',  z_star)
    
    print('..............................................................')
    
    print('Probability of state ' , utility_params['state']  ,' on untainted data: ', p_untainted_data )
    
    print('...............................................................')
    
    print('Probability of state ' , utility_params['state'] ,' on tainted data: ', p_tainted_data)
    


### Attraction

#### Case 1: $w_1 >> w_2$

t = 3

In [6]:
utility_params = {'state':0 , 'w1':100000, 'w2':1, 'c':1, 't':3}
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    utility_params['t'] = t
    print()
    for state in range(3):
        utility_params['state'] = state
        print('Attraction to state ', utility_params['state'])
        example_attraction_repulsion(g_w_dict,  x_vector, utility_params)
        print()

t =  1

Attraction to state  0



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.7797191295930866

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.7274065499902806

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  2  on untainted data:  0.32799326136230866
...............................................................
Probability of state  2  on tainted data:  0.3662187066945257

t =  2

Attraction to state  0



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.5562474414073794
...............................................................
Probability of state  0  on tainted data:  0.8502004324419137

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.34875106498557634
...............................................................
Probability of state  1  on tainted data:  0.8597058560688566

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  2  on untainted data:  0.09500149360704432
...............................................................
Probability of state  2  on tainted data:  0.23286093557419107

t =  3

Attraction to state  0



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.5748434260315521
...............................................................
Probability of state  0  on tainted data:  0.8556292138453222

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.3562831544890554
...............................................................
Probability of state  1  on tainted data:  0.9007830139526644

Attraction to state  2



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  2  on untainted data:  0.0688734194793924
...............................................................
Probability of state  2  on tainted data:  0.1962566708948993

t =  4

Attraction to state  0



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.5301662151066322
...............................................................
Probability of state  0  on tainted data:  0.8419545748874712

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.3896965862318206
...............................................................
Probability of state  1  on tainted data:  0.901021884534411

Attraction to state  2



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  2  on untainted data:  0.08013719866154721
...............................................................
Probability of state  2  on tainted data:  0.1936129368527035

t =  5

Attraction to state  0



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.3734003469712001
...............................................................
Probability of state  0  on tainted data:  0.8084919786293737

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.45404543391321966
...............................................................
Probability of state  1  on tainted data:  0.8672484211616069

Attraction to state  2



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.17255421911558017
...............................................................
Probability of state  2  on tainted data:  0.19869796383449512



#### Case 2: $w_1 << w_2$

In [7]:
utility_params = {'state':0 , 'w1':1, 'w2':100000, 'c':1, 't':3}
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    utility_params['t'] = t
    print()
    for state in range(3):
        utility_params['state'] = state
        print('Attraction to state ', utility_params['state'])
        example_attraction_repulsion(g_w_dict,  x_vector, utility_params)
        print()

t =  1

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.3352593014784263

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.33674743715926514

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.32799326136230866
...............................................................
Probability of state  2  on tainted data:  0.32799326136230866

t =  2

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.5562474414073794
...............................................................
Probability of state  0  on tainted data:  0.5562474414073794

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.34875106498557634
...............................................................
Probability of state  1  on tainted data:  0.34875106498557634

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.09500149360704432
...............................................................
Probability of state  2  on tainted data:  0.09500149360704432

t =  3

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.5748434260315521
...............................................................
Probability of state  0  on tainted data:  0.5748434260315521

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.3562831544890554
...............................................................
Probability of state  1  on tainted data:  0.3562831544890554

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.0688734194793924
...............................................................
Probability of state  2  on tainted data:  0.0688734194793924

t =  4

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.5301662151066322
...............................................................
Probability of state  0  on tainted data:  0.5301662151066322

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.3896965862318206
...............................................................
Probability of state  1  on tainted data:  0.3896965862318206

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.08013719866154721
...............................................................
Probability of state  2  on tainted data:  0.08013719866154721

t =  5

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3734003469712001
...............................................................
Probability of state  0  on tainted data:  0.3734003469712001

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.45404543391321966
...............................................................
Probability of state  1  on tainted data:  0.45404543391321966

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.17255421911558017
...............................................................
Probability of state  2  on tainted data:  0.17255421911558017



#### Case 3: $w_1 = 0.95, w_2 = 0.05$

In [14]:
utility_params = {'state':0 , 'w1':0.95, 'w2':0.05, 'c': 1, 't':3}
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    utility_params['t'] = t
    print()
    for state in range(3):
        utility_params['state'] = state
        print('Attraction to state ', utility_params['state'])
        example_attraction_repulsion(g_w_dict,  x_vector, utility_params)
        print()

t =  1

Attraction to state  0



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.7797191295930866

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.6856249673252792

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.32799326136230866
...............................................................
Probability of state  2  on tainted data:  0.32799326136230866

t =  2

Attraction to state  0



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.5562474414073794
...............................................................
Probability of state  0  on tainted data:  0.8502004324419137

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.34875106498557634
...............................................................
Probability of state  1  on tainted data:  0.8597058560688566

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  2  on untainted data:  0.09500149360704432
...............................................................
Probability of state  2  on tainted data:  0.23286093557419107

t =  3

Attraction to state  0



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.5748434260315521
...............................................................
Probability of state  0  on tainted data:  0.8556292138453222

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.3562831544890554
...............................................................
Probability of state  1  on tainted data:  0.9007830139526644

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.0688734194793924
...............................................................
Probability of state  2  on tainted data:  0.12751379112434422

t =  4

Attraction to state  0



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.5301662151066322
...............................................................
Probability of state  0  on tainted data:  0.8419545748874712

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.3896965862318206
...............................................................
Probability of state  1  on tainted data:  0.901021884534411

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.08013719866154721
...............................................................
Probability of state  2  on tainted data:  0.13915920651289382

t =  5

Attraction to state  0



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.3734003469712001
...............................................................
Probability of state  0  on tainted data:  0.8084919786293737

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.45404543391321966
...............................................................
Probability of state  1  on tainted data:  0.8265977472010393

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.17255421911558017
...............................................................
Probability of state  2  on tainted data:  0.17255421911558017



#### Repulsion 

 * Case 1: $w_1 >> w_2$

In [9]:
utility_params = {'state':0 , 'w1':100000, 'w2':1, 'c':-1, 't':3}
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    utility_params['t'] = t
    print()
    for state in range(3):
        utility_params['state'] = state
        print('Attraction to state ', utility_params['state'])
        example_attraction_repulsion(g_w_dict,  x_vector, utility_params)
        print()

t =  1

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.06525140111581962

Attraction to state  1



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.08250034869203672

Attraction to state  2



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  2  on untainted data:  0.32799326136230866
...............................................................
Probability of state  2  on tainted data:  0.1377805217148765

t =  2

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.5562474414073794
...............................................................
Probability of state  0  on tainted data:  0.04254505972487675

Attraction to state  1



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.34875106498557634
...............................................................
Probability of state  1  on tainted data:  0.08035477909569222

Attraction to state  2



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  2  on untainted data:  0.09500149360704432
...............................................................
Probability of state  2  on tainted data:  0.0694447884623941

t =  3

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.5748434260315521
...............................................................
Probability of state  0  on tainted data:  0.0318273515271133

Attraction to state  1



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.3562831544890554
...............................................................
Probability of state  1  on tainted data:  0.08245246808354077

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.0688734194793924
...............................................................
Probability of state  2  on tainted data:  0.059779182321254565

t =  4

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.5301662151066322
...............................................................
Probability of state  0  on tainted data:  0.03370684820025636

Attraction to state  1



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.3896965862318206
...............................................................
Probability of state  1  on tainted data:  0.0948431266122516

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.08013719866154721
...............................................................
Probability of state  2  on tainted data:  0.05751647138533353

t =  5

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3734003469712001
...............................................................
Probability of state  0  on tainted data:  0.05389176994852645

Attraction to state  1



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.45404543391321966
...............................................................
Probability of state  1  on tainted data:  0.12132662548027402

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  2  on untainted data:  0.17255421911558017
...............................................................
Probability of state  2  on tainted data:  0.06457576840082456



#### Case 2:   $w_2 >> w_1$

In [10]:
utility_params = {'state':0 , 'w1':1, 'w2':100000, 'c':-1, 't':3}
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    utility_params['t'] = t
    print()
    for state in range(3):
        utility_params['state'] = state
        print('Attraction to state ', utility_params['state'])
        example_attraction_repulsion(g_w_dict,  x_vector, utility_params)
        print()

t =  1

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.3352593014784263

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.33674743715926514

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.32799326136230866
...............................................................
Probability of state  2  on tainted data:  0.32799326136230866

t =  2

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.5562474414073794
...............................................................
Probability of state  0  on tainted data:  0.5562474414073794

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.34875106498557634
...............................................................
Probability of state  1  on tainted data:  0.34875106498557634

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.09500149360704432
...............................................................
Probability of state  2  on tainted data:  0.09500149360704432

t =  3

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.5748434260315521
...............................................................
Probability of state  0  on tainted data:  0.5748434260315521

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.3562831544890554
...............................................................
Probability of state  1  on tainted data:  0.3562831544890554

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.0688734194793924
...............................................................
Probability of state  2  on tainted data:  0.0688734194793924

t =  4

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.5301662151066322
...............................................................
Probability of state  0  on tainted data:  0.5301662151066322

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.3896965862318206
...............................................................
Probability of state  1  on tainted data:  0.3896965862318206

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.08013719866154721
...............................................................
Probability of state  2  on tainted data:  0.08013719866154721

t =  5

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3734003469712001
...............................................................
Probability of state  0  on tainted data:  0.3734003469712001

Attraction to state  1



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.45404543391321966
...............................................................
Probability of state  1  on tainted data:  0.45404543391321966

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.17255421911558017
...............................................................
Probability of state  2  on tainted data:  0.17255421911558017



#### Case 3: $w_1 = 0.95, w_2 = 0.05$

In [13]:
utility_params = {'state':0 , 'w1':0.95, 'w2':0.05, 'c':-1, 't':3}
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    utility_params['t'] = t
    print()
    for state in range(3):
        utility_params['state'] = state
        print('Attraction to state ', utility_params['state'])
        example_attraction_repulsion(g_w_dict,  x_vector, utility_params)
        print()

t =  1

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.08771018904681316

Attraction to state  1



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.08250034869203672

Attraction to state  2



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.32799326136230866
...............................................................
Probability of state  2  on tainted data:  0.140105958390479

t =  2

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.5562474414073794
...............................................................
Probability of state  0  on tainted data:  0.07696701398281286

Attraction to state  1



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.34875106498557634
...............................................................
Probability of state  1  on tainted data:  0.08035477909569222

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.09500149360704432
...............................................................
Probability of state  2  on tainted data:  0.09500149360704432

t =  3

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.5748434260315521
...............................................................
Probability of state  0  on tainted data:  0.0318273515271133

Attraction to state  1



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.3562831544890554
...............................................................
Probability of state  1  on tainted data:  0.08245246808354077

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.0688734194793924
...............................................................
Probability of state  2  on tainted data:  0.0688734194793924

t =  4

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.5301662151066322
...............................................................
Probability of state  0  on tainted data:  0.06708886518115025

Attraction to state  1



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.3896965862318206
...............................................................
Probability of state  1  on tainted data:  0.0948431266122516

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  2  on untainted data:  0.08013719866154721
...............................................................
Probability of state  2  on tainted data:  0.08013719866154721

t =  5

Attraction to state  0



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3734003469712001
...............................................................
Probability of state  0  on tainted data:  0.08076169930205102

Attraction to state  1



Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.45404543391321966
...............................................................
Probability of state  1  on tainted data:  0.12132662548027402

Attraction to state  2



Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  2  on untainted data:  0.17255421911558017
...............................................................
Probability of state  2  on tainted data:  0.06919879815352105

