In [1]:
import numpy as np

# Standard Viterbi

In [2]:
priors     = np.array([0.5,0.5])
transition = np.array([[0.95, 0.1],[0.05, 0.9]])
emission   = np.array([[1/6, 1/6, 1/6, 1/6, 1/6, 1/6],
                       [0.1, 0.1, 0.1, 0.1, 0.1, 0.5]]).T

In [3]:
def run_Viterbi(real_obs, emission, transition):
    
    V   = np.zeros([len(real_obs), 2]) 
    Ptr = np.zeros([len(real_obs), 2]) 

    # Init
    V[0] = emission[real_obs[0]] * priors

    # Forward
    for t in np.arange(1 , len(real_obs) ):
        
        #print(V[t-1])

        V[t]   =  emission[real_obs[t]] * np.max( transition * V[t-1], axis=1 )
        Ptr[t] =  np.argmax( transition * V[t-1], axis=1 )

    # Backward

    z_max = np.zeros(len(real_obs), dtype=int)

    z_max[-1] = np.argmax(V[-1])

    for t in np.arange(len(real_obs)-2, -1, -1):    
        z_max[t] = Ptr[t, z_max[t+1]]
        
    return z_max


In [11]:
real_seq_labels = np.array(["S","S","S","S","S","S","S","S","S","S","S","S","S","S","I","I","I","I",
                     "I","I","S","S","S","S","S","S","S","S","S","S","S","S","S","S","I","I",
                     "I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","S","S",
                     "S","S","S","S","S","S","S","S","S","S","S","S","S","I","I","I","S","S",
                     "S","S","S","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I",
                     "I","I","I","I","I","I","I","I","I","I","I","I","I","S","S","S","S","S",
                     "S","S","S","S","S","S","S","S","S","S","S","S","S","S","S","S","S","S",
                     "I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I",
                     "I","I","I","I","I","S","S","S","S","S","S","S","S","S","S","I","I","I",
                     "I","I","S","S","I","I","I","I","I","I","I","I","I","I","I","I","I","I",
                     "I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I",
                     "I","I","I","I","I","I","I","I","I","I","I","I","S","S","S","S","I","I",
                     "I","I","I","I","I","I","I","I","I","S","S","S","S","S","S","S","S","I",
                     "I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I",
                     "I","I","I","I","I","I","S","S","S","S","I","I","I","I","I","I","I","I",
                     "S","S","S","S","S","S","S","S","S","S","S","S","S","I","I","I","S","S",
                     "S","S","S","S","S","S","S","S","I","I","S","S"])


real_seq = np.zeros_like(real_seq_labels, dtype=int)
real_seq[real_seq_labels=="S"] = 1

real_obs = np.zeros_like(real_seq)

for i, j in enumerate(real_seq):
    p = emission[:,j]
    real_obs[i] = np.random.choice(np.arange(0,6), p=p)
    
    
print(list(real_obs))
    
MAP_seq = run_Viterbi(real_obs, emission, transition) 

print(list(MAP_seq))


np.mean(MAP_seq == real_seq)

[5, 0, 5, 2, 3, 5, 5, 5, 5, 2, 3, 5, 3, 5, 0, 5, 4, 3, 2, 1, 5, 5, 5, 0, 5, 2, 5, 5, 5, 5, 1, 5, 5, 4, 5, 2, 0, 3, 1, 5, 3, 1, 3, 3, 2, 1, 1, 4, 5, 4, 4, 1, 0, 0, 2, 4, 1, 4, 3, 0, 5, 5, 1, 5, 5, 0, 2, 1, 5, 4, 5, 5, 5, 1, 5, 2, 2, 2, 4, 1, 0, 2, 4, 0, 2, 5, 3, 1, 4, 3, 0, 1, 4, 4, 5, 3, 2, 5, 2, 1, 1, 2, 4, 2, 2, 4, 1, 4, 5, 5, 3, 5, 4, 5, 4, 5, 4, 0, 0, 5, 3, 0, 0, 5, 0, 5, 5, 2, 1, 2, 0, 2, 2, 1, 5, 1, 5, 1, 0, 1, 3, 3, 1, 3, 3, 4, 4, 3, 5, 2, 0, 0, 5, 5, 5, 5, 5, 1, 5, 4, 2, 0, 2, 0, 2, 3, 1, 5, 0, 3, 5, 2, 5, 5, 4, 1, 1, 3, 3, 5, 0, 1, 2, 3, 3, 4, 3, 3, 1, 3, 5, 5, 4, 0, 3, 5, 5, 5, 1, 0, 4, 2, 1, 3, 0, 4, 0, 2, 1, 1, 2, 5, 2, 2, 2, 1, 1, 3, 3, 1, 1, 3, 0, 0, 4, 5, 4, 4, 5, 2, 4, 5, 2, 3, 1, 4, 2, 2, 0, 3, 5, 3, 5, 3, 1, 0, 4, 1, 1, 5, 1, 3, 2, 0, 3, 0, 0, 0, 3, 1, 3, 0, 4, 3, 4, 0, 2, 1, 0, 3, 2, 5, 5, 5, 1, 5, 1, 5, 1, 4, 4, 2, 1, 3, 3, 2, 2, 0, 5, 5, 5, 3, 5, 3, 5, 5, 5, 0, 1, 5]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

0.7133333333333334

# Attacking Viterbi

In [5]:
real_seq_labels = np.array(["S","S","S","S","S","S","S","S","S"])

real_seq = np.zeros_like(real_seq_labels, dtype=int)
real_seq[real_seq_labels=="S"] = 1

real_obs = np.zeros_like(real_seq)

for i, j in enumerate(real_seq):
    p = emission[:,j]
    real_obs[i] = np.random.choice(np.arange(0,6), p=p)

In [6]:
print( "Real Obs: ", real_obs)


inferred_real_seq = run_Viterbi(real_obs, emission, transition)
print( "Inferred Seq: ", inferred_real_seq)

target_seq = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1])
print( "Target Seq: ", target_seq)

Real Obs:  [5 5 3 5 5 5 2 5 2]
Inferred Seq:  [0 1 1 1 1 1 1 1 1]
Target Seq:  [0 0 0 0 1 1 1 1 1]


In [16]:
def g1(x, theta2_opt):
    return transition[theta2_opt] * emission[x] * priors

def V_tilde1(x):
    return emission[x] * priors

def g(x, theta_opt, V_tilde):
    return transition[theta_opt] * emission[x] * np.max( transition * V_tilde, axis=1 )

def next_V_tilde(x, V_tilde):
    return emission[x] * np.max( transition * V_tilde, axis=1 )

In [58]:
# 0, 1, 1

g1(2, 0)
# obs0 = 2

g(5, 1, V_tilde1(2))
# obs1 = 5

curr_V_tilde = next_V_tilde(5, V_tilde1(2))

#curr_V_tilde
next_V_tilde(5, curr_V_tilde)
# obs2 = 


array([0.00208912, 0.010125  ])

In [64]:
cont_data = np.array([2,5,5,3,4,5])
run_Viterbi(cont_data, emission, transition)

[0.08333333 0.05      ]
[0.01319444 0.0225    ]
[0.00208912 0.010125  ]
[0.00033078 0.00091125]
[5.23730871e-05 8.20125000e-05]


array([0, 1, 1, 1, 1, 1])

In [49]:
g1(4, 0)

array([0.07916667, 0.005     ])

In [34]:
emission[5]

array([0.16666667, 0.5       ])

In [18]:
target_seq = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [22]:
transition[0]

array([0.95, 0.1 ])