In [1]:
import numpy as np
from hmm_utils import HMM
from smoothing_state_attacker import ss_attacker
from extra import monte_carlo_enumeration

In [2]:
#HMM A , B, pi

priors     = np.array([0.5,0.3,0.2])
transition = np.array([[0.85, 0.05,0.1],
                       [0.05, 0.9,0.05],
                        [1/2, 1/4, 1/4]])
emission   = np.array([[1/6, 1/6, 1/6, 1/6, 1/6, 1/6],
                    [0.1, 0.1, 0.1, 0.1, 0.1, 0.5],
                       [0.1, 0.1, 0.1, 0.1, 0.1, 0.5]])

In [3]:
# initialize HMM
hmm = HMM(n_components=3,n_obs=6)
hmm.startprob_ = priors
hmm.transmat_ = transition
hmm.emissionprob_ = emission

g_w_dict = {'A': transition,
      'B': emission,
      'pi': priors}

In [9]:
def example_attraction_repulsion(g_w_dict,  x_vector, ss_att):
    
    z_star = monte_carlo_enumeration_state_attraction_repulsion(hmm = hmm,
                                                                ss_att = ss_att,
                                                                g_w = g_w_dict,
                                                                N = 1,
                                                                x_vector = x_vector,
                                                                utility_function = ss_att.utility)
    
    y_vec =  hmm.attack_X(x_vector.reshape(5,1), np.ones([len(x_vector),6]),z_star).astype('int')
    
    compute_prob_att = ss_attacker(w1 = ss_att.w1 ,w2= ss_att.w2,t = ss_att.t, state=ss_att.state,c=1)
    p_untainted_data = compute_prob_att.state_attraction_repulsion_f1(alpha = hmm.alpha(x_vector), beta = hmm.beta(x_vector))
    p_tainted_data = compute_prob_att.state_attraction_repulsion_f1(alpha = hmm.alpha(y_vec), beta = hmm.beta(y_vec))
    
    print('Best attack',  z_star)
    
    print('..............................................................')
    
    print('Probability of state ' , ss_att.state  ,' on untainted data: ', p_untainted_data )
    
    print('...............................................................')
    
    print('Probability of state ' , ss_att.state ,' on tainted data: ', p_tainted_data)
    


In [4]:
def example_attraction_repulsion_with_random_rho(hmm, k_value, attacker,  N, x_vector, theta_prob_vec):
    
    z_star = monte_carlo_enumeration(hmm, k_value, attacker,  N, x_vector, theta_prob_vec)[0]
    
    y_vec =  hmm.attack_X(x_vector.reshape(5,1), np.ones([len(x_vector),6]),z_star).astype('int')
    
    compute_prob_att = ss_attacker(w1 = ss_att.w1 ,w2= ss_att.w2,t = ss_att.t, state=ss_att.state,c=1)
    p_untainted_data = compute_prob_att.state_attraction_repulsion_f1(alpha = hmm.alpha(x_vector), beta = hmm.beta(x_vector))
    p_tainted_data = compute_prob_att.state_attraction_repulsion_f1(alpha = hmm.alpha(y_vec), beta = hmm.beta(y_vec))
    
    print('Best attack',  z_star)
    
    print('..............................................................')
    
    print('Probability of state ' , ss_att.state  ,' on untainted data: ', p_untainted_data )
    
    print('...............................................................')
    
    print('Probability of state ' , ss_att.state ,' on tainted data: ', p_tainted_data)
    


### Attraction

#### Case 1: $w_1 >> w_2$

##### No constant

In [12]:
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    print()
    for state in range(3):
        ss_att = ss_attacker(w1 = 100000 ,w2= 1 ,t = t, state= state,c=1)
        print('Attraction to state ', ss_att.state)
        example_attraction_repulsion_with_random_rho(hmm, 100, ss_att, 18 , x_vector, np.array([0.9,0.9,0.9,0.9,0.9,0.9]))        
        print()

t =  1

Attraction to state  0
Best attack [[0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.7797191295930866

Attraction to state  1
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.7274065499902806

Attraction to state  2
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
............................................................

##### Constant

In [5]:
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    print()
    for state in range(3):
        ss_att = ss_attacker(w1 = 100000 ,w2= 1 ,t = t, state= state,c=1)
        print('Attraction to state ', ss_att.state)
        example_attraction_repulsion(g_w_dict,  x_vector, ss_att)
        print()

t =  1

Attraction to state  0
Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.7797191295930866

Attraction to state  1
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.7274065499902806

Attraction to state  2
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
............................................................

#### Case 2: $w_1 << w_2$

##### No constant

In [13]:
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    print()
    for state in range(3):
        ss_att = ss_attacker(w1 = 1  ,w2= 100000 ,t = t, state= state,c=1)
        print('Attraction to state ', ss_att.state)
        example_attraction_repulsion_with_random_rho(hmm, 100, ss_att, 18 , x_vector, np.array([0.9,0.9,0.9,0.9,0.9,0.9]))        
        print()

t =  1

Attraction to state  0
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.3352593014784263

Attraction to state  1
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.33674743715926514

Attraction to state  2
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
...........................................................

##### Constant 

In [6]:
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    print()
    for state in range(3):
        ss_att = ss_attacker(w1 = 1  ,w2= 100000 ,t = t, state= state,c=1)
        print('Attraction to state ', ss_att.state)
        example_attraction_repulsion(g_w_dict,  x_vector, ss_att)
        print()

t =  1

Attraction to state  0
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.3352593014784263

Attraction to state  1
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.33674743715926514

Attraction to state  2
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
...........................................................

#### Case 3: $w_1 = 0.95, w_2 = 0.05$

##### No constant

In [14]:
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    print()
    for state in range(3):
        ss_att = ss_attacker(w1 = 0.95 ,w2= 0.05 ,t = t, state= state,c=1)
        print('Attraction to state ', ss_att.state)
        example_attraction_repulsion_with_random_rho(hmm, 100, ss_att, 18 , x_vector, np.array([0.9,0.9,0.9,0.9,0.9,0.9]))        
        print()

t =  1

Attraction to state  0
Best attack [[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.7797191295930866

Attraction to state  1
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.6856249673252792

Attraction to state  2
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
............................................................

##### Constant

In [7]:
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    print()
    for state in range(3):
        ss_att = ss_attacker(w1 = 0.95 ,w2= 0.05 ,t = t, state= state,c=1)
        print('Attraction to state ', ss_att.state)
        example_attraction_repulsion(g_w_dict,  x_vector, ss_att)
        print()

t =  1

Attraction to state  0
Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.7797191295930866

Attraction to state  1
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.6856249673252792

Attraction to state  2
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
............................................................

#### Repulsion 

 * Case 1: $w_1 >> w_2$

##### No constant

In [16]:
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    print()
    for state in range(3):
        ss_att = ss_attacker(w1 = 100000 ,w2= 1 ,t = t, state= state,c=-1)
        print('Attraction to state ', ss_att.state)
        example_attraction_repulsion_with_random_rho(hmm, 100, ss_att, 18 , x_vector, np.array([0.9,0.9,0.9,0.9,0.9,0.9]))        
        print()

t =  1

Attraction to state  0
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.06525140111581962

Attraction to state  1
Best attack [[0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.08250034869203672

Attraction to state  2
Best attack [[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..........................................................

##### Constant

In [8]:
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    print()
    for state in range(3):
        ss_att = ss_attacker(w1 = 100000 ,w2= 1 ,t = t, state= state,c=-1)
        print('Attraction to state ', ss_att.state)
        example_attraction_repulsion(g_w_dict,  x_vector, ss_att)
        print()

t =  1

Attraction to state  0
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.06525140111581962

Attraction to state  1
Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.08250034869203672

Attraction to state  2
Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..........................................................

#### Case 2:   $w_2 >> w_1$

##### No constant

In [17]:
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    print()
    for state in range(3):
        ss_att = ss_attacker(w1 = 1 ,w2= 100000 ,t = t, state= state,c=-1)
        print('Attraction to state ', ss_att.state)
        example_attraction_repulsion_with_random_rho(hmm, 100, ss_att, 18 , x_vector, np.array([0.9,0.9,0.9,0.9,0.9,0.9]))        
        print()

t =  1

Attraction to state  0
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.3352593014784263

Attraction to state  1
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.33674743715926514

Attraction to state  2
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
...........................................................

##### Constant

In [9]:
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    print()
    for state in range(3):
        ss_att = ss_attacker(w1 = 1 ,w2= 100000 ,t = t, state= state,c=-1)
        print('Attraction to state ', ss_att.state)
        example_attraction_repulsion(g_w_dict,  x_vector, ss_att)
        print()

t =  1

Attraction to state  0
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.3352593014784263

Attraction to state  1
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.33674743715926514

Attraction to state  2
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
...........................................................

#### Case 3: $w_1 = 0.95, w_2 = 0.05$

##### No constant

In [18]:
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    print()
    for state in range(3):
        ss_att = ss_attacker(w1 = 0.95 ,w2= 0.05 ,t = t, state= state,c=-1)
        print('Attraction to state ', ss_att.state)
        example_attraction_repulsion_with_random_rho(hmm, 100, ss_att, 18 , x_vector, np.array([0.9,0.9,0.9,0.9,0.9,0.9]))        
        print()

t =  1

Attraction to state  0
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.08771018904681316

Attraction to state  1
Best attack [[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.08250034869203672

Attraction to state  2
Best attack [[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..........................................................

##### Constant 

In [10]:
x_vector = np.array([ [5], [3], [4], [3], [5]])
t_range = range(1,6)
for t in t_range:
    print('t = ', t)
    print()
    for state in range(3):
        ss_att = ss_attacker(w1 = 0.95 ,w2= 0.05 ,t = t, state= state,c=-1)
        print('Attraction to state ', ss_att.state)
        example_attraction_repulsion(g_w_dict,  x_vector, ss_att)
        print()

t =  1

Attraction to state  0
Best attack [[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..............................................................
Probability of state  0  on untainted data:  0.3352593014784263
...............................................................
Probability of state  0  on tainted data:  0.08771018904681316

Attraction to state  1
Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
..............................................................
Probability of state  1  on untainted data:  0.33674743715926514
...............................................................
Probability of state  1  on tainted data:  0.08250034869203672

Attraction to state  2
Best attack [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
..........................................................