In [2]:
from solvers.RS_NN.nn_RS import *
from attackers.smoothing_state_attacker import *

In [4]:
priors     = np.array([0.5,0.3,0.2])
transition = np.array([[0.85, 0.05,0.1],
                       [0.05, 0.9,0.05],
                        [1/2, 1/4, 1/4]])

emission   = np.array([[0.699, 0.05, 0.1, 0.05, 0.1, 0.001],
                    [0.001, 0.1, 0.1, 0.299, 0.3, 0.2],
                       [0.1, 0.2, 0.1, 0.2, 0.1, 0.3]])

rho_probs = np.ones(6)

x_vector = np.array([ [5], [3], [4], [3], [5]])

attacker = ss_attacker(priors, transition, emission, rho_probs,
         x_vector, w1 = 1.0 ,w2 = 0.0 , t = 3, state= 0, c=1, k_value=100000)

In [7]:
attacker.n_obs

np.arange(attacker.n_obs)

array([0, 1, 2, 3, 4, 5])

In [2]:
initial_conf = -1*np.ones(50)
initial_conf[0] = 0.
initial_conf

array([ 0., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [3]:
init_state = boolean_optim_state(initial_conf)
root_node  = boolean_optim_mcts_node(init_state)
search     = boolean_optim_mcts(root_node)

In [4]:
search.iterate(total_simulation_seconds=10)

array([0., 2., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Optimizing NN

In [11]:
import torch
from torch import nn
import torch.nn.functional as F
import numpy as np
from torch.optim import Adam



In [10]:
def policy():
    pass

def update(output, nn_output, model, optim):
    
    ll = loss(nn_output, real_output)
    optim.zero_grad()
    ll.backward()
    optim.step()

In [8]:
w = torch.tensor([-0.7, -0.5, -2.0, -3.0, 1.5, 8.0])
def evaluate(z):
    return torch.dot(z,w.T)

In [12]:
model  = FeedForwardNN(6, 1)
optim  = Adam(model.parameters(), lr=0.001)
loss   = nn.MSELoss()

In [13]:
obs = torch.tensor([0.,1.,0.,1.,1.,0.])
F_eval = lambda x: model.forward(x).detach().numpy().item()

In [14]:
F_eval(obs)

-0.10444967448711395

In [15]:
initial_conf = -1*np.ones(6)
init_state = boolean_optim_state(initial_conf, np.array([0,1]), F_eval)
root_node  = boolean_optim_mcts_node(init_state)
search     = boolean_optim_mcts(root_node)
search.iterate(total_simulation_seconds=10)

In [12]:
obs = torch.tensor([1.,0.,0.,0.,0.,0.])


In [14]:
for i in range(1000):
    obs = torch.tensor([0.,1.,0.,1.,0.,0.])
    real_output = evaluate(obs)
    nn_output   = model.forward(obs)
    update(real_output, nn_output, model, optim)
    print( model.forward(obs) )

/home/roi/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py:520: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


tensor([-0.0996], grad_fn=<AddBackward0>)
tensor([-0.1246], grad_fn=<AddBackward0>)
tensor([-0.1492], grad_fn=<AddBackward0>)
tensor([-0.1741], grad_fn=<AddBackward0>)
tensor([-0.1992], grad_fn=<AddBackward0>)
tensor([-0.2242], grad_fn=<AddBackward0>)
tensor([-0.2489], grad_fn=<AddBackward0>)
tensor([-0.2739], grad_fn=<AddBackward0>)
tensor([-0.2989], grad_fn=<AddBackward0>)
tensor([-0.3236], grad_fn=<AddBackward0>)
tensor([-0.3483], grad_fn=<AddBackward0>)
tensor([-0.3734], grad_fn=<AddBackward0>)
tensor([-0.3992], grad_fn=<AddBackward0>)
tensor([-0.4256], grad_fn=<AddBackward0>)
tensor([-0.4526], grad_fn=<AddBackward0>)
tensor([-0.4793], grad_fn=<AddBackward0>)
tensor([-0.5063], grad_fn=<AddBackward0>)
tensor([-0.5341], grad_fn=<AddBackward0>)
tensor([-0.5624], grad_fn=<AddBackward0>)
tensor([-0.5913], grad_fn=<AddBackward0>)
tensor([-0.6211], grad_fn=<AddBackward0>)
tensor([-0.6518], grad_fn=<AddBackward0>)
tensor([-0.6831], grad_fn=<AddBackward0>)
tensor([-0.7149], grad_fn=<AddBack

tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBack

tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBack

tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBackward0>)
tensor([-3.5000], grad_fn=<AddBack

In [15]:
a = np.array([1, 0, 0, 2, 3])

In [17]:
np.diag(np.ones(6))[a]

array([[0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])