In [110]:
import numpy as np
from hmmlearn import hmm

In [111]:
from sklearn.hmm import MultinomialHMM

ModuleNotFoundError: No module named 'sklearn.hmm'

In [30]:
priors     = np.array([0.5,0.5])
transition = np.array([[0.95, 0.05],[0.1, 0.9]])
emission   = np.array([[1/6, 1/6, 1/6, 1/6, 1/6, 1/6],
                       [0.1, 0.1, 0.1, 0.1, 0.1, 0.5]])

In [130]:
class HMM(hmm.MultinomialHMM):
    
    def __init__(self, n_components, priors=None, 
                 transition=None, xemission=None):
        
        super().__init__(n_components)
        
        if ( (priors is not None) & (transition is not None) 
            & (emission is not None) ):
            
            print("hola")
            
            self.startprob_ = priors
            self.transmat_ = transition
            self.emissionprob_ = emission
            
    def smoothing(self, X, t):
        return model.predict_proba(X)[t]
    
    def alpha(self, X):
        pass
    
    def beta(self, X):
        pass
    
    def nu(self, X):
        pass
    
        
        
        

In [135]:
m = HMM(n_components=2)

In [133]:
m.emissionprob_

array([[0.20716324, 0.19456016, 0.32540586, 0.02769612, 0.03024142,
        0.2149332 ],
       [0.08531885, 0.14058855, 0.01647782, 0.25060537, 0.191139  ,
        0.31587043]])

In [132]:
X = np.atleast_2d([5, 0, 5, 2, 3, 5, 5, 5, 5, 2, 3, 5, 3, 5, 0, 5, 4, 3, 2, 1, 5, 5, 5, 0, 5, 2, 5, 5, 5, 5, 1, 5, 5, 4, 5, 2, 0, 3, 1, 5, 3, 1, 3, 3, 2, 1, 1, 4, 5, 4, 4, 1, 0, 0, 2, 4, 1, 4, 3, 0, 5, 5, 1, 5, 5, 0, 2, 1, 5, 4, 5, 5, 5, 1, 5, 2, 2, 2, 4, 1, 0, 2, 4, 0, 2, 5, 3, 1, 4, 3, 0, 1, 4, 4, 5, 3, 2, 5, 2, 1, 1, 2, 4, 2, 2, 4, 1, 4, 5, 5, 3, 5, 4, 5, 4, 5, 4, 0, 0, 5, 3, 0, 0, 5, 0, 5, 5, 2, 1, 2, 0, 2, 2, 1, 5, 1, 5, 1, 0, 1, 3, 3, 1, 3, 3, 4, 4, 3, 5, 2, 0, 0, 5, 5, 5, 5, 5, 1, 5, 4, 2, 0, 2, 0, 2, 3, 1, 5, 0, 3, 5, 2, 5, 5, 4, 1, 1, 3, 3, 5, 0, 1, 2, 3, 3, 4, 3, 3, 1, 3, 5, 5, 4, 0, 3, 5, 5, 5, 1, 0, 4, 2, 1, 3, 0, 4, 0, 2, 1, 1, 2, 5, 2, 2, 2, 1, 1, 3, 3, 1, 1, 3, 0, 0, 4, 5, 4, 4, 5, 2, 4, 5, 2, 3, 1, 4, 2, 2, 0, 3, 5, 3, 5, 3, 1, 0, 4, 1, 1, 5, 1, 3, 2, 0, 3, 0, 0, 0, 3, 1, 3, 0, 4, 3, 4, 0, 2, 1, 0, 3, 2, 5, 5, 5, 1, 5, 1, 5, 1, 4, 4, 2, 1, 3, 3, 2, 2, 0, 5, 5, 5, 3, 5, 3, 5, 5, 5, 0, 1, 5]).T
m.fit(X)

HMM(n_components=2)

In [63]:

# Predict the optimal sequence of internal hidden state
X = np.atleast_2d([5, 0, 5, 2, 3, 5, 5, 5, 5, 2, 3, 5, 3, 5, 0, 5, 4, 3, 2, 1, 5, 5, 5, 0, 5, 2, 5, 5, 5, 5, 1, 5, 5, 4, 5, 2, 0, 3, 1, 5, 3, 1, 3, 3, 2, 1, 1, 4, 5, 4, 4, 1, 0, 0, 2, 4, 1, 4, 3, 0, 5, 5, 1, 5, 5, 0, 2, 1, 5, 4, 5, 5, 5, 1, 5, 2, 2, 2, 4, 1, 0, 2, 4, 0, 2, 5, 3, 1, 4, 3, 0, 1, 4, 4, 5, 3, 2, 5, 2, 1, 1, 2, 4, 2, 2, 4, 1, 4, 5, 5, 3, 5, 4, 5, 4, 5, 4, 0, 0, 5, 3, 0, 0, 5, 0, 5, 5, 2, 1, 2, 0, 2, 2, 1, 5, 1, 5, 1, 0, 1, 3, 3, 1, 3, 3, 4, 4, 3, 5, 2, 0, 0, 5, 5, 5, 5, 5, 1, 5, 4, 2, 0, 2, 0, 2, 3, 1, 5, 0, 3, 5, 2, 5, 5, 4, 1, 1, 3, 3, 5, 0, 1, 2, 3, 3, 4, 3, 3, 1, 3, 5, 5, 4, 0, 3, 5, 5, 5, 1, 0, 4, 2, 1, 3, 0, 4, 0, 2, 1, 1, 2, 5, 2, 2, 2, 1, 1, 3, 3, 1, 1, 3, 0, 0, 4, 5, 4, 4, 5, 2, 4, 5, 2, 3, 1, 4, 2, 2, 0, 3, 5, 3, 5, 3, 1, 0, 4, 1, 1, 5, 1, 3, 2, 0, 3, 0, 0, 0, 3, 1, 3, 0, 4, 3, 4, 0, 2, 1, 0, 3, 2, 5, 5, 5, 1, 5, 1, 5, 1, 4, 4, 2, 1, 3, 3, 2, 2, 0, 5, 5, 5, 3, 5, 3, 5, 5, 5, 0, 1, 5]).T
a,b = m.decode(X)

In [64]:
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], d

In [81]:
model = hmm.MultinomialHMM(n_components=2)


model.fit(X)

MultinomialHMM(n_components=2,
               random_state=<mtrand.RandomState object at 0x7f97746f4708>)

In [82]:
model.transmat_

array([[0.48309489, 0.51690511],
       [0.31890982, 0.68109018]])

In [46]:
type(model)

hmmlearn.hmm.MultinomialHMM

In [39]:
model.predict_proba(X)

array([[0.11667453, 0.88332547],
       [0.13277204, 0.86722796],
       [0.11029436, 0.88970564],
       [0.13131088, 0.86868912],
       [0.11389275, 0.88610725],
       [0.05188896, 0.94811104],
       [0.03310498, 0.96689502],
       [0.03453964, 0.96546036],
       [0.05794971, 0.94205029],
       [0.13200102, 0.86799898],
       [0.15700189, 0.84299811],
       [0.14178104, 0.85821896],
       [0.17759529, 0.82240471],
       [0.1712072 , 0.8287928 ],
       [0.22423809, 0.77576191],
       [0.23058063, 0.76941937],
       [0.31325839, 0.68674161],
       [0.34068603, 0.65931397],
       [0.32254926, 0.67745074],
       [0.25244333, 0.74755667],
       [0.10561121, 0.89438879],
       [0.05665062, 0.94334938],
       [0.04560884, 0.95439116],
       [0.05896512, 0.94103488],
       [0.04116348, 0.95883652],
       [0.04649336, 0.95350664],
       [0.02186484, 0.97813516],
       [0.0148694 , 0.9851306 ],
       [0.01694107, 0.98305893],
       [0.03061662, 0.96938338],
       [0.

In [43]:
model.

ConvergenceMonitor(
    history=[],
    iter=0,
    n_iter=10,
    tol=0.01,
    verbose=False,
)