#### hmm_utils.py

In [1]:
from hmm_utils import *

In [2]:
priors     = np.array([0.5,0.3,0.2])
transition = np.array([[0.85, 0.05,0.1],
                       [0.05, 0.9,0.05],
                        [1/2, 1/4, 1/4]])
emission   = np.array([[1/6, 1/6, 1/6, 1/6, 1/6, 1/6],
                    [0.1, 0.1, 0.1, 0.1, 0.1, 0.5],
                       [0.1, 0.1, 0.1, 0.1, 0.1, 0.5]])

print('---------- Initialize HMM ---------')

# initialize HMM

hmm = HMM(3, 6)
hmm.startprob_ = priors
hmm.transmat_ = transition
hmm.emissionprob_ = emission

print(hmm)

print('Priors'   , hmm.startprob_)

print('Transition matrix')
print(hmm.transmat_)

print('Emission probabilities')
print(hmm.emissionprob_)

X = hmm.sample(5)[0]
print('Observation X')
print(X)
print('Probability of states at time t=4 ---smoothing')
print(hmm.smoothing(X,1))
print('Compute alphas--(log probabilities)')
print(hmm.alpha(X))
print('Compute betas--(log probabilities)')
print(hmm.beta(X))
print('Compute sample matrix ---(high variance)')
print('----transition matrix----')
print(hmm.sample_mat(hmm.transmat_, n=1, k=10000))
print('----emission matrix----')
print(hmm.sample_mat(hmm.emissionprob_, n=1, k=10000))
print('----priors vector-----')
print(hmm.sample_mat(np.array([[0.5,0.3,0.2]]) ,n=1, k=10000))
print('Compute sample rho - Prob. succesful attack')
rho_matrix = hmm.sample_rho(len(X), [0.5, 0.7, 0.6, 0.2 , 0.5, 0.7])
print(rho_matrix)
print('Compute an attack over observations')
print('---------observations--------------')
print(X)
print('---------prob.succesful attack------')
print(rho_matrix)
print('---------attack matrix ------------')
z_matrix = np.zeros((len(X),hmm.n_obs))
z_matrix[:,0] = 1
print(z_matrix)
print('------------compute attacked observations ----------')
Y = (hmm.attack_X(X, rho_matrix, z_matrix))
print(Y)
print('------------ generate Z set ------------------')
Z_set = hmm.generate_z(5)
print(Z_set)

---------- Initialize HMM ---------
HMM(n_components=3, n_obs=6)
Priors [0.5 0.3 0.2]
Transition matrix
[[0.85 0.05 0.1 ]
 [0.05 0.9  0.05]
 [0.5  0.25 0.25]]
Emission probabilities
[[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.1        0.1        0.1        0.1        0.1        0.5       ]
 [0.1        0.1        0.1        0.1        0.1        0.5       ]]
Observation X
[[1]
 [4]
 [5]
 [4]
 [0]]
Probability of states at time t=4 ---smoothing
[0.66623048 0.18866425 0.14510527]
Compute alphas--(log probabilities)
[[ -2.48490665  -3.5065579   -3.91202301]
 [ -4.2887387   -5.62220249  -6.51346347]
 [ -6.16689877  -6.13951351  -6.94655386]
 [ -7.83584763  -8.38364719  -9.79363298]
 [ -9.67943064 -10.63981746 -11.94508017]]
Compute betas--(log probabilities)
[[-7.20421423 -7.4442297  -7.30127409]
 [-5.37374958 -5.15904669 -5.15261497]
 [-3.72785131 -4.48541379 -3.96477936]
 [-1.85363487 -2.26979527 -2.01490302]
 [ 0.          0.          0.        ]]
Compute sa

#### smoothing_state_attacker.py

In [3]:
from smoothing_state_attacker import ss_attacker

In [4]:
ss_att = ss_attacker(w1 = 2 ,w2=  2,t = 1, state=1,c=1)

In [5]:
hmm = HMM(2, 6)

priors     = np.array([0.5,0.3,0.2])
transition = np.array([[0.85, 0.05,0.1],
                       [0.05, 0.9,0.05],
                        [1/2, 1/4, 1/4]])
emission   = np.array([[1/6, 1/6, 1/6, 1/6, 1/6, 1/6],
                    [0.1, 0.1, 0.1, 0.1, 0.1, 0.5],
                       [0.1, 0.1, 0.1, 0.1, 0.1, 0.5]])


# initialize HMM

hmm = HMM(3, 6)
hmm.startprob_ = priors
hmm.transmat_ = transition
hmm.emissionprob_ = emission
X = hmm.sample(5)[0]



priors     = np.array([0.5,0.5])
transition = np.array([[0.95, 0.05],[0.1, 0.9]])
emission   = np.array([[1/6, 1/6, 1/6, 1/6, 1/6, 1/6],
                    [0.1, 0.1, 0.1, 0.1, 0.1, 0.5]])

    
print('Initialize HMM')
# initialize HMM
hmm = HMM(2, 6)
hmm.startprob_ = priors
hmm.transmat_ = transition
hmm.emissionprob_ = emission

print(hmm)

print('Priors', hmm.startprob_)
print('Transition matrix')
print(hmm.transmat_)
print('Emission probabilities')
print(hmm.emissionprob_)

print('Observations --- X')
X = hmm.sample(5)[0]    
print(X)
print('Attacked observations --Y_t')
y_t = np.ones((5)).reshape(5,1).astype('int')
print(y_t)
print('---------attack matrix ------------')
z_matrix = np.zeros((len(X),hmm.n_obs))
z_matrix[:,0] = 1
print(z_matrix)


print('Initialize smoothing_state_attacker')
ss_att = ss_attacker(w1 = 2 ,w2=  2,t = 1, state=1,c=1)
print('w1',ss_att.w1)
print('w2',ss_att.w1)
print('t', ss_att.t)
print('state',ss_att.state)
print('c', ss_att.c)
print('Utility f1')
print(ss_att.state_attraction_repulsion_f1(hmm.alpha(X), hmm.beta(X)))
print('Utility f2')
print(ss_att.f2_function(z_matrix, X))
print('Utility')
print(ss_att.utility(hmm, z_matrix, X, y_t))

Initialize HMM
HMM(n_components=2, n_obs=6)
Priors [0.5 0.5]
Transition matrix
[[0.95 0.05]
 [0.1  0.9 ]]
Emission probabilities
[[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.1        0.1        0.1        0.1        0.1        0.5       ]]
Observations --- X
[[5]
 [4]
 [5]
 [0]
 [5]]
Attacked observations --Y_t
[[1]
 [1]
 [1]
 [1]
 [1]]
---------attack matrix ------------
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]
Initialize smoothing_state_attacker
w1 2
w2 2
t 1
state 1
c 1
Utility f1
0.8471005781923202
Utility f2
4
Utility
-7.686930601405085


#### extra

In [6]:
ss_att = ss_attacker(w1 = 6767 ,w2=  1,t = 1, state=1,c=1)
    
g_w_dict = {'A': transition,
      'B': emission,
      'pi': priors}

utility_params_1 = {'state':ss_att.state , 'w1':ss_att.w1, 'w2':ss_att.w2, 'c':ss_att.c, 't':ss_att.t}

In [7]:
def monte_carlo_enumeration_state_attraction_repulsion(hmm, ss_att, g_w, N, x_vector, utility_function ):
    
    n_states, n_obs = g_w['B'].shape
    print(n_states,n_obs)
    Z_set = hmm.generate_z(len(x_vector))
    Z_len = len(Z_set)
    u_z_vector = np.zeros(Z_len) 
    
    for i_z,z_matrix in (enumerate(Z_set)):
        
        sum_u_values  = 0 
        
        for n in range(N):
            
            transtion_mat = g_w['A']
            emission_mat = g_w['B']
            priors_vec = g_w['pi']
            hmm_n = HMM(n_states, n_obs)
            print(hmm_n)
            hmm_n.startprob_ = priors_vec
            hmm_n.transmat_ = transtion_mat
            hmm_n.emissionprob_ = emission_mat
            rho_matrix = np.ones([len(x_vector),n_obs]) 
            y_t = hmm.attack_X(X= x_vector, z_matrix = z_matrix, rho_matrix = rho_matrix).astype('int')
            u_value = utility_function(hmm = hmm_n, z_matrix = z_matrix, x_obs_vector = x_vector, y_t = y_t)
            sum_u_values += u_value
            
        u_z_vector[i_z] = sum_u_values/N
                        
    arg_max = np.argmax(u_z_vector)
    z_star = Z_set[arg_max]
    
    return z_star 




In [8]:
monte_carlo_enumeration_state_attraction_repulsion(hmm ,ss_att  ,g_w = g_w_dict, N = 1, x_vector = X, utility_function = ss_att.utility)

2 6
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_comp

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_components=2, n_obs=6)
HMM(n_componen

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]])

In [9]:
ss_att = ss_attacker(w1 = 2 ,w2=  2,t = 1, state=1,c=1)

#### General montecarlo

In [10]:
ss_att = ss_attacker(w1 = 6767 ,w2=  1,t = 1, state=1,c=1)
    
g_w_dict = {'A': hmm.sample_mat(hmm.transmat_, n=1, k=10000)[0],
      'B': hmm.sample_mat(hmm.emissionprob_, n=1, k=10)[0],
      'pi': hmm.sample_mat(np.array([list(hmm.startprob_)]) ,n=1, k=10000).reshape(-1)}



In [11]:
print(hmm.n_components, hmm.n_obs)
hmm.sample_mat(np.array([list(hmm.startprob_)]) ,n=1, k=10000).reshape(-1)

2 6


array([0.49672679, 0.50327321])

In [12]:
hmm.sample_mat(hmm.transmat_, n=5, k=10)

array([[[0.99323958, 0.00676042],
        [0.22059045, 0.77940955]],

       [[0.86609394, 0.13390606],
        [0.10620764, 0.89379236]],

       [[0.95957488, 0.04042512],
        [0.1061399 , 0.8938601 ]],

       [[0.95244553, 0.04755447],
        [0.31331914, 0.68668086]],

       [[0.86703319, 0.13296681],
        [0.07082521, 0.92917479]]])

In [13]:
def monte_carlo_enumeration_state_attraction_repulsion(hmm, ss_att, N, x_vector, utility_function, g_w = None):
    
    Z_set = hmm.generate_z(len(x_vector))
    Z_len = len(Z_set)
    u_z_vector = np.zeros(Z_len) 
    
    for i_z,z_matrix in (enumerate(Z_set)):
        
        sum_u_values  = 0 
        
        for n in range(N):
            
            transtion_mat = hmm.sample_mat(hmm.transmat_, n=1, k=10)[0]
            emission_mat = hmm.sample_mat(hmm.emissionprob_, n=1, k=10)[0]
            priors_vec = hmm.sample_mat(np.array([list(hmm.startprob_)]), n=1, k=10).reshape(-1)
            hmm_n = HMM(hmm.n_components, hmm.n_obs)
            hmm_n.startprob_ = priors_vec
            hmm_n.transmat_ = transtion_mat
            hmm_n.emissionprob_ = emission_mat
            rho_matrix = np.ones([len(x_vector),hmm.n_obs]) 
            y_t = hmm.attack_X(X= x_vector, z_matrix = z_matrix, rho_matrix = rho_matrix).astype('int')
            u_value = utility_function(hmm = hmm_n, z_matrix = z_matrix, x_obs_vector = x_vector, y_t = y_t)
            sum_u_values += u_value
            
        u_z_vector[i_z] = sum_u_values/N
                        
    arg_max = np.argmax(u_z_vector)
    z_star = Z_set[arg_max]
    
    return z_star 




In [14]:
transtion_mat = hmm.sample_mat(hmm.transmat_, n=1, k=10)[0]
emission_mat = hmm.sample_mat(hmm.emissionprob_, n=1, k=10)[0]
priors_vec = hmm.sample_mat(np.array([list(hmm.startprob_)]), n=1, k=10).reshape(-1)

In [15]:
def monte_carlo_enumeration_state_attraction_repulsion(hmm, k_value, ss_att, N, x_vector):
    
    Z_set = hmm.generate_z(len(x_vector))
    u_z_matrix = np.zeros((len(Z_set), N)) 
    transtion_mat_list = hmm.sample_mat(hmm.transmat_, n= N, k= k_value)
    emission_mat_list = hmm.sample_mat(hmm.emissionprob_, n= N, k= k_value)
    priors_vec_list = hmm.sample_mat(np.array([list(hmm.startprob_)]), n=N, k=k_value)

    for i_z,z_matrix in (enumerate(Z_set)):  
        
        for n in range(N):
            
            hmm_n = HMM(hmm.n_components, hmm.n_obs)
            hmm_n.startprob_ = priors_vec_list[n].reshape(-1)
            hmm_n.transmat_ = transtion_mat_list[n]
            hmm_n.emissionprob_ = emission_mat_list[n]
            rho_matrix = np.ones([len(x_vector),hmm.n_obs]) 
            y_t = hmm.attack_X(X= x_vector, z_matrix = z_matrix, rho_matrix = rho_matrix).astype('int')
            u_value = ss_att.utility_function(hmm = hmm_n, z_matrix = z_matrix, x_obs_vector = x_vector, y_t = y_t)
            u_z_matrix[i_z][n] = u_value
            
    u_z_vector = np.mean(u_z_matrix, axis=1)     
    arg_max = np.argmax(u_z_vector)
    z_star = Z_set[arg_max]
    
    return z_star, u_z_vector




#### Montecarlo with random rho

In [16]:
def monte_carlo_enumeration(hmm, k_value, attacker,  N, x_vector, theta_prob_vec):
    
    Z_set = hmm.generate_z(len(x_vector))
    u_z_matrix = np.zeros((len(Z_set), N)) 
    transtion_mat_list = hmm.sample_mat(hmm.transmat_, n= N, k= k_value)
    emission_mat_list = hmm.sample_mat(hmm.emissionprob_, n= N, k= k_value)
    priors_vec_list = hmm.sample_mat(np.array([list(hmm.startprob_)]), n=N, k=k_value)
    rho_matrix_list = hmm.sample_rho(T= N, theta_v = theta_prob_vec)
    
    for i_z,z_matrix in (enumerate(Z_set)):  
        
        for n in range(N):
            hmm_n = HMM(hmm.n_components, hmm.n_obs)
            hmm_n.startprob_ = priors_vec_list[n].reshape(-1)
            hmm_n.transmat_ = transtion_mat_list[n]
            hmm_n.emissionprob_ = emission_mat_list[n]
            rho_matrix = rho_matrix_list[n]
            y_t = hmm.attack_X(X= x_vector, z_matrix = z_matrix, rho_matrix = rho_matrix).astype('int')
            u_value = attacker.utility(hmm = hmm_n, z_matrix = z_matrix, x_obs_vector = x_vector, y_t = y_t)
            u_z_matrix[i_z][n] = u_value
            
    u_z_vector = np.mean(u_z_matrix, axis=1)     
    arg_max = np.argmax(u_z_vector)
    z_star = Z_set[arg_max]
    
    return z_star, u_z_vector


In [17]:
X

array([[5],
       [4],
       [5],
       [0],
       [5]])

In [19]:
monte_carlo_enumeration(hmm, k_value = 0.1, attacker = ss_att, N = 10, x_vector = X , theta_prob_vec = np.array([0.95,0.95,0.95,0.95,0.95,0.95]))

/home/jmcamachor/poisoning_hmms/smoothing_state_attacker.py:34: RuntimeWarning: invalid value encountered in true_divide
  p /= np.sum(p)


(array([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.]]),
 array([3380.00192452, 3379.49999946, 3394.37668322, ..., 5434.71706189,
        6078.43506561, 5411.60000024]))